package kr.hs.entrydsm.application.entity;

import java.time.LocalDate;

public abstract class EntityTest {

    protected final Applicant graduateCommonMale = Applicant.builder()
            .receiptCode(1)
            .telephoneNumber("01012345678")
            .applicationType(ApplicationType.COMMON)
            .educationalStatus(EducationalStatus.GRADUATE)
            .isDaejeon(true)
            .name("김빵빵")
            .sex(Sex.MALE)
            .birthday(LocalDate.of(2004, 3, 14))
            .parentName("김빵붕")
            .parentTel("01087654321")
            .address("대한민국 어딘가")
            .postCode("12345")
            .photoFileName("사진 이름")
            .homeTel("0421234567")
            .selfIntroduce("자기소개")
            .studyPlan("학업계획")
            .build();

    protected final Applicant graduateCommonFemale = Applicant.builder()
            .receiptCode(1)
            .telephoneNumber("01012345678")
            .applicationType(ApplicationType.COMMON)
            .educationalStatus(EducationalStatus.GRADUATE)
            .isDaejeon(true)
            .name("김빵빵")
            .sex(Sex.FEMALE)
            .birthday(LocalDate.of(2004, 3, 14))
            .parentName("김빵붕")
            .parentTel("01087654321")
            .address("대한민국 어딘가")
            .postCode("12345")
            .photoFileName("사진 이름")
            .homeTel("0421234567")
            .selfIntroduce("자기소개")
            .studyPlan("학업계획")
            .build();

    protected final Applicant graduateMeisterMale = Applicant.builder()
            .receiptCode(1)
            .telephoneNumber("01012345678")
            .applicationType(ApplicationType.MEISTER)
            .educationalStatus(EducationalStatus.GRADUATE)
            .isDaejeon(true)
            .name("김빵빵")
            .sex(Sex.MALE)
            .birthday(LocalDate.of(2004, 3, 14))
            .parentName("김빵붕")
            .parentTel("01087654321")
            .address("대한민국 어딘가")
            .postCode("12345")
            .photoFileName("사진 이름")
            .homeTel("0421234567")
            .selfIntroduce("자기소개")
            .studyPlan("학업계획")
            .build();

    protected final Applicant graduateMeisterFemale = Applicant.builder()
            .receiptCode(1)
            .telephoneNumber("01012345678")
            .applicationType(ApplicationType.MEISTER)
            .educationalStatus(EducationalStatus.GRADUATE)
            .isDaejeon(true)
            .name("김빵빵")
            .sex(Sex.FEMALE)
            .birthday(LocalDate.of(2004, 3, 14))
            .parentName("김빵붕")
            .parentTel("01087654321")
            .address("대한민국 어딘가")
            .postCode("12345")
            .photoFileName("사진 이름")
            .homeTel("0421234567")
            .selfIntroduce("자기소개")
            .studyPlan("학업계획")
            .build();

    protected final Applicant graduateSocialMale = Applicant.builder()
            .receiptCode(1)
            .telephoneNumber("01012345678")
            .applicationType(ApplicationType.SOCIAL)
            .educationalStatus(EducationalStatus.GRADUATE)
            .isDaejeon(true)
            .name("김빵빵")
            .sex(Sex.MALE)
            .birthday(LocalDate.of(2004, 3, 14))
            .parentName("김빵붕")
            .parentTel("01087654321")
            .address("대한민국 어딘가")
            .postCode("12345")
            .photoFileName("사진 이름")
            .homeTel("0421234567")
            .selfIntroduce("자기소개")
            .studyPlan("학업계획")
            .build();

    protected final Applicant graduateSocialFemale = Applicant.builder()
            .receiptCode(1)
            .telephoneNumber("01012345678")
            .applicationType(ApplicationType.SOCIAL)
            .educationalStatus(EducationalStatus.GRADUATE)
            .isDaejeon(true)
            .name("김빵빵")
            .sex(Sex.FEMALE)
            .birthday(LocalDate.of(2004, 3, 14))
            .parentName("김빵붕")
            .parentTel("01087654321")
            .address("대한민국 어딘가")
            .postCode("12345")
            .photoFileName("사진 이름")
            .homeTel("0421234567")
            .selfIntroduce("자기소개")
            .studyPlan("학업계획")
            .build();

    protected final Applicant prospectiveGraduateCommonMale = Applicant.builder()
            .receiptCode(1)
            .telephoneNumber("01012345678")
            .applicationType(ApplicationType.COMMON)
            .educationalStatus(EducationalStatus.PROSPECTIVE_GRADUATE)
            .isDaejeon(true)
            .name("김빵빵")
            .sex(Sex.MALE)
            .birthday(LocalDate.of(2004, 3, 14))
            .parentName("김빵붕")
            .parentTel("01087654321")
            .address("대한민국 어딘가")
            .postCode("12345")
            .photoFileName("사진 이름")
            .homeTel("0421234567")
            .selfIntroduce("자기소개")
            .studyPlan("학업계획")
            .build();

    protected final Applicant prospectiveGraduateCommonFemale = Applicant.builder()
            .receiptCode(1)
            .telephoneNumber("01012345678")
            .applicationType(ApplicationType.COMMON)
            .educationalStatus(EducationalStatus.PROSPECTIVE_GRADUATE)
            .isDaejeon(true)
            .name("김빵빵")
            .sex(Sex.FEMALE)
            .birthday(LocalDate.of(2004, 3, 14))
            .parentName("김빵붕")
            .parentTel("01087654321")
            .address("대한민국 어딘가")
            .postCode("12345")
            .photoFileName("사진 이름")
            .homeTel("0421234567")
            .selfIntroduce("자기소개")
            .studyPlan("학업계획")
            .build();

    protected final Applicant prospectiveGraduateMeisterMale = Applicant.builder()
            .receiptCode(1)
            .telephoneNumber("01012345678")
            .applicationType(ApplicationType.MEISTER)
            .educationalStatus(EducationalStatus.PROSPECTIVE_GRADUATE)
            .isDaejeon(true)
            .name("김빵빵")
            .sex(Sex.MALE)
            .birthday(LocalDate.of(2004, 3, 14))
            .parentName("김빵붕")
            .parentTel("01087654321")
            .address("대한민국 어딘가")
            .postCode("12345")
            .photoFileName("사진 이름")
            .homeTel("0421234567")
            .selfIntroduce("자기소개")
            .studyPlan("학업계획")
            .build();

    protected final Applicant prospectiveGraduateMeisterFemale = Applicant.builder()
            .receiptCode(1)
            .telephoneNumber("01012345678")
            .applicationType(ApplicationType.MEISTER)
            .educationalStatus(EducationalStatus.PROSPECTIVE_GRADUATE)
            .isDaejeon(true)
            .name("김빵빵")
            .sex(Sex.FEMALE)
            .birthday(LocalDate.of(2004, 3, 14))
            .parentName("김빵붕")
            .parentTel("01087654321")
            .address("대한민국 어딘가")
            .postCode("12345")
            .photoFileName("사진 이름")
            .homeTel("0421234567")
            .selfIntroduce("자기소개")
            .studyPlan("학업계획")
            .build();

    protected final Applicant prospectiveGraduateSocialMale = Applicant.builder()
            .receiptCode(1)
            .telephoneNumber("01012345678")
            .applicationType(ApplicationType.SOCIAL)
            .educationalStatus(EducationalStatus.PROSPECTIVE_GRADUATE)
            .isDaejeon(true)
            .name("김빵빵")
            .sex(Sex.MALE)
            .birthday(LocalDate.of(2004, 3, 14))
            .parentName("김빵붕")
            .parentTel("01087654321")
            .address("대한민국 어딘가")
            .postCode("12345")
            .photoFileName("사진 이름")
            .homeTel("0421234567")
            .selfIntroduce("자기소개")
            .studyPlan("학업계획")
            .build();

    protected final Applicant prospectiveGraduateSocialFemale = Applicant.builder()
            .receiptCode(1)
            .telephoneNumber("01012345678")
            .applicationType(ApplicationType.SOCIAL)
            .educationalStatus(EducationalStatus.PROSPECTIVE_GRADUATE)
            .isDaejeon(true)
            .name("김빵빵")
            .sex(Sex.FEMALE)
            .birthday(LocalDate.of(2004, 3, 14))
            .parentName("김빵붕")
            .parentTel("01087654321")
            .address("대한민국 어딘가")
            .postCode("12345")
            .photoFileName("사진 이름")
            .homeTel("0421234567")
            .selfIntroduce("자기소개")
            .studyPlan("학업계획")
            .build();

    protected final Applicant qualificationExamCommonMale = Applicant.builder()
            .receiptCode(1)
            .telephoneNumber("01012345678")
            .applicationType(ApplicationType.COMMON)
            .educationalStatus(EducationalStatus.QUALIFICATION_EXAM)
            .isDaejeon(true)
            .name("김빵빵")
            .sex(Sex.MALE)
            .birthday(LocalDate.of(2004, 3, 14))
            .parentName("김빵붕")
            .parentTel("01087654321")
            .address("대한민국 어딘가")
            .postCode("12345")
            .photoFileName("사진 이름")
            .homeTel("0421234567")
            .selfIntroduce("자기소개")
            .studyPlan("학업계획")
            .build();

    protected final Applicant qualificationExamCommonFemale = Applicant.builder()
            .receiptCode(1)
            .telephoneNumber("01012345678")
            .applicationType(ApplicationType.COMMON)
            .educationalStatus(EducationalStatus.QUALIFICATION_EXAM)
            .isDaejeon(true)
            .name("김빵빵")
            .sex(Sex.FEMALE)
            .birthday(LocalDate.of(2004, 3, 14))
            .parentName("김빵붕")
            .parentTel("01087654321")
            .address("대한민국 어딘가")
            .postCode("12345")
            .photoFileName("사진 이름")
            .homeTel("0421234567")
            .selfIntroduce("자기소개")
            .studyPlan("학업계획")
            .build();

    protected final Applicant qualificationExamMeisterMale = Applicant.builder()
            .receiptCode(1)
            .telephoneNumber("01012345678")
            .applicationType(ApplicationType.MEISTER)
            .educationalStatus(EducationalStatus.QUALIFICATION_EXAM)
            .isDaejeon(true)
            .name("김빵빵")
            .sex(Sex.MALE)
            .birthday(LocalDate.of(2004, 3, 14))
            .parentName("김빵붕")
            .parentTel("01087654321")
            .address("대한민국 어딘가")
            .postCode("12345")
            .photoFileName("사진 이름")
            .homeTel("0421234567")
            .selfIntroduce("자기소개")
            .studyPlan("학업계획")
            .build();

    protected final Applicant qualificationExamMeisterFemale = Applicant.builder()
            .receiptCode(1)
            .telephoneNumber("01012345678")
            .applicationType(ApplicationType.MEISTER)
            .educationalStatus(EducationalStatus.QUALIFICATION_EXAM)
            .isDaejeon(true)
            .name("김빵빵")
            .sex(Sex.FEMALE)
            .birthday(LocalDate.of(2004, 3, 14))
            .parentName("김빵붕")
            .parentTel("01087654321")
            .address("대한민국 어딘가")
            .postCode("12345")
            .photoFileName("사진 이름")
            .homeTel("0421234567")
            .selfIntroduce("자기소개")
            .studyPlan("학업계획")
            .build();

    protected final Applicant qualificationExamSocialMale = Applicant.builder()
            .receiptCode(1)
            .telephoneNumber("01012345678")
            .applicationType(ApplicationType.SOCIAL)
            .educationalStatus(EducationalStatus.QUALIFICATION_EXAM)
            .isDaejeon(true)
            .name("김빵빵")
            .sex(Sex.MALE)
            .birthday(LocalDate.of(2004, 3, 14))
            .parentName("김빵붕")
            .parentTel("01087654321")
            .address("대한민국 어딘가")
            .postCode("12345")
            .photoFileName("사진 이름")
            .homeTel("0421234567")
            .selfIntroduce("자기소개")
            .studyPlan("학업계획")
            .build();

    protected final Applicant qualificationExamSocialFemale = Applicant.builder()
            .receiptCode(1)
            .telephoneNumber("01012345678")
            .applicationType(ApplicationType.SOCIAL)
            .educationalStatus(EducationalStatus.QUALIFICATION_EXAM)
            .isDaejeon(true)
            .name("김빵빵")
            .sex(Sex.FEMALE)
            .birthday(LocalDate.of(2004, 3, 14))
            .parentName("김빵붕")
            .parentTel("01087654321")
            .address("대한민국 어딘가")
            .postCode("12345")
            .photoFileName("사진 이름")
            .homeTel("0421234567")
            .selfIntroduce("자기소개")
            .studyPlan("학업계획")
            .build();

    protected final Applicant basicLiving = Applicant.builder()
            .applicationRemark(ApplicationRemark.BASIC_LIVING)
            .build();

    protected final Applicant fromNorth = Applicant.builder()
            .applicationRemark(ApplicationRemark.FROM_NORTH)
            .build();

    protected final Applicant lowestIncome = Applicant.builder()
            .applicationRemark(ApplicationRemark.LOWEST_INCOME)
            .build();

    protected final Applicant multicultural = Applicant.builder()
            .applicationRemark(ApplicationRemark.MULTICULTURAL)
            .build();

    protected final Applicant oneParent = Applicant.builder()
            .applicationRemark(ApplicationRemark.ONE_PARENT)
            .build();

    protected final Applicant teenHouseholder = Applicant.builder()
            .applicationRemark(ApplicationRemark.TEEN_HOUSEHOLDER)
            .build();

    protected final Applicant privilegedAdmission = Applicant.builder()
            .applicationRemark(ApplicationRemark.PRIVILEGED_ADMISSION)
            .build();

    protected final Applicant nationalMerit = Applicant.builder()
            .applicationRemark(ApplicationRemark.NATIONAL_MERIT)
            .build();

}
