server:
  port: 8888

spring:
  datasource:
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}

auth:
  jwt:
    secret: ${JWT_SECRET_KEY:dGVzdA==}
    exp:
      access: ${JWT_ACCESS_EXP:3600}
      refresh: ${JWT_REFRESH_EXP:3600}
    header:
      access: ${JWT_HEADER:Authorization}
    prefix: ${JWT_PREFIX:Bearer}

aws:
  s3:
    accessKey: ${AWS_S3_ACCESS:s3_access}
    secretKey: ${AWS_S3_SECRET:s3_secret}
    region: ${AWS_S3_REGION:ap-northeast-2}
  ses:
    access-key: ${AWS_SES_ACCESS:ses_access}
    secret_key: ${AWS_SES_SECRET:ses_secret}
    region: ${AWS_SES_REGION:ap-northeast-2}

munchkin:
  logging:
    name: munchkin.log
    path: ${LOG_PATH:/}
    size: 10 # 10mb