server:
  port: 8888

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

auth:
  jwt:
    secret: ${JWT_SECRET_KEY:dGVzdA==}
    exp:
      access: ${JWT_ACCESS_EXP:3600}
      refresh: ${JWT_REFRESH_EXP:3600}
    header:
      access: ${JWT_HEADER:Authorization}
      refresh: ${JWT_REFRESH_HEADER:X-Refresh-Token}
    prefix: ${JWT_PREFIX:Bearer}

munchkin:
  logging:
    name: munchkin.log
    path: ${LOG_PATH:/}
    size: 10 # 10mb